// Create types
export const VENTA_CREATE_ERROR = 'VENTA_CREATE_ERROR';
export const VENTA_CREATE_LOADING = 'VENTA_CREATE_LOADING';
export const VENTA_CREATE_SUCCESS = 'VENTA_CREATE_SUCCESS';
export const VENTA_CREATE_VIOLATIONS = 'VENTA_CREATE_VIOLATIONS';
export const VENTA_CREATE_RESET = 'VENTA_CREATE_RESET';

// Show types
export const VENTA_SHOW_ERROR = 'VENTA_SHOW_ERROR';
export const VENTA_SHOW_LOADING = 'VENTA_SHOW_LOADING';
export const VENTA_SHOW_RETRIEVED_SUCCESS = 'VENTA_SHOW_RETRIEVED_SUCCESS';
export const VENTA_SHOW_RESET = 'VENTA_SHOW_RESET';

// Update types
export const VENTA_UPDATE_RESET = 'VENTA_UPDATE_RESET';
export const VENTA_UPDATE_UPDATE_ERROR = 'VENTA_UPDATE_UPDATE_ERROR';
export const VENTA_UPDATE_UPDATE_LOADING = 'VENTA_UPDATE_UPDATE_LOADING';
export const VENTA_UPDATE_UPDATE_SUCCESS = 'VENTA_UPDATE_UPDATE_SUCCESS';
export const VENTA_UPDATE_RETRIEVE_ERROR = 'VENTA_UPDATE_RETRIEVE_ERROR';
export const VENTA_UPDATE_RETRIEVE_LOADING = 'VENTA_UPDATE_RETRIEVE_LOADING';
export const VENTA_UPDATE_RETRIEVE_SUCCESS = 'VENTA_UPDATE_RETRIEVE_SUCCESS';
export const VENTA_UPDATE_UPDATE_VIOLATIONS = 'VENTA_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const VENTA_DELETE_ERROR = 'VENTA_DELETE_ERROR';
export const VENTA_DELETE_LOADING = 'VENTA_DELETE_LOADING';
export const VENTA_DELETE_SUCCESS = 'VENTA_DELETE_SUCCESS';
export const VENTA_DELETE_RESET = 'VENTA_DELETE_RESET';

// List types
export const VENTA_LIST_ERROR = 'VENTA_LIST_ERROR';
export const VENTA_LIST_LOADING = 'VENTA_LIST_LOADING';
export const VENTA_LIST_RESET = 'VENTA_LIST_RESET';
export const VENTA_LIST_VIEW = 'VENTA_LIST_VIEW';
export const VENTA_LIST_SUCCESS = 'VENTA_LIST_SUCCESS';
