// Create types
export const PEDIDO_CREATE_ERROR = 'PEDIDO_CREATE_ERROR';
export const PEDIDO_CREATE_LOADING = 'PEDIDO_CREATE_LOADING';
export const PEDIDO_CREATE_SUCCESS = 'PEDIDO_CREATE_SUCCESS';
export const PEDIDO_CREATE_VIOLATIONS = 'PEDIDO_CREATE_VIOLATIONS';
export const PEDIDO_CREATE_RESET = 'PEDIDO_CREATE_RESET';

// Show types
export const PEDIDO_SHOW_ERROR = 'PEDIDO_SHOW_ERROR';
export const PEDIDO_SHOW_LOADING = 'PEDIDO_SHOW_LOADING';
export const PEDIDO_SHOW_RETRIEVED_SUCCESS = 'PEDIDO_SHOW_RETRIEVED_SUCCESS';
export const PEDIDO_SHOW_RESET = 'PEDIDO_SHOW_RESET';

// Update types
export const PEDIDO_UPDATE_RESET = 'PEDIDO_UPDATE_RESET';
export const PEDIDO_UPDATE_UPDATE_ERROR = 'PEDIDO_UPDATE_UPDATE_ERROR';
export const PEDIDO_UPDATE_UPDATE_LOADING = 'PEDIDO_UPDATE_UPDATE_LOADING';
export const PEDIDO_UPDATE_UPDATE_SUCCESS = 'PEDIDO_UPDATE_UPDATE_SUCCESS';
export const PEDIDO_UPDATE_RETRIEVE_ERROR = 'PEDIDO_UPDATE_RETRIEVE_ERROR';
export const PEDIDO_UPDATE_RETRIEVE_LOADING = 'PEDIDO_UPDATE_RETRIEVE_LOADING';
export const PEDIDO_UPDATE_RETRIEVE_SUCCESS = 'PEDIDO_UPDATE_RETRIEVE_SUCCESS';
export const PEDIDO_UPDATE_UPDATE_VIOLATIONS = 'PEDIDO_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const PEDIDO_DELETE_ERROR = 'PEDIDO_DELETE_ERROR';
export const PEDIDO_DELETE_LOADING = 'PEDIDO_DELETE_LOADING';
export const PEDIDO_DELETE_SUCCESS = 'PEDIDO_DELETE_SUCCESS';
export const PEDIDO_DELETE_RESET = 'PEDIDO_DELETE_RESET';

// List types
export const PEDIDO_LIST_ERROR = 'PEDIDO_LIST_ERROR';
export const PEDIDO_LIST_LOADING = 'PEDIDO_LIST_LOADING';
export const PEDIDO_LIST_RESET = 'PEDIDO_LIST_RESET';
export const PEDIDO_LIST_VIEW = 'PEDIDO_LIST_VIEW';
export const PEDIDO_LIST_SUCCESS = 'PEDIDO_LIST_SUCCESS';
