// Create types
export const TALLA_CREATE_ERROR = 'TALLA_CREATE_ERROR';
export const TALLA_CREATE_LOADING = 'TALLA_CREATE_LOADING';
export const TALLA_CREATE_SUCCESS = 'TALLA_CREATE_SUCCESS';
export const TALLA_CREATE_VIOLATIONS = 'TALLA_CREATE_VIOLATIONS';
export const TALLA_CREATE_RESET = 'TALLA_CREATE_RESET';

// Show types
export const TALLA_SHOW_ERROR = 'TALLA_SHOW_ERROR';
export const TALLA_SHOW_LOADING = 'TALLA_SHOW_LOADING';
export const TALLA_SHOW_RETRIEVED_SUCCESS = 'TALLA_SHOW_RETRIEVED_SUCCESS';
export const TALLA_SHOW_RESET = 'TALLA_SHOW_RESET';

// Update types
export const TALLA_UPDATE_RESET = 'TALLA_UPDATE_RESET';
export const TALLA_UPDATE_UPDATE_ERROR = 'TALLA_UPDATE_UPDATE_ERROR';
export const TALLA_UPDATE_UPDATE_LOADING = 'TALLA_UPDATE_UPDATE_LOADING';
export const TALLA_UPDATE_UPDATE_SUCCESS = 'TALLA_UPDATE_UPDATE_SUCCESS';
export const TALLA_UPDATE_RETRIEVE_ERROR = 'TALLA_UPDATE_RETRIEVE_ERROR';
export const TALLA_UPDATE_RETRIEVE_LOADING = 'TALLA_UPDATE_RETRIEVE_LOADING';
export const TALLA_UPDATE_RETRIEVE_SUCCESS = 'TALLA_UPDATE_RETRIEVE_SUCCESS';
export const TALLA_UPDATE_UPDATE_VIOLATIONS = 'TALLA_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TALLA_DELETE_ERROR = 'TALLA_DELETE_ERROR';
export const TALLA_DELETE_LOADING = 'TALLA_DELETE_LOADING';
export const TALLA_DELETE_SUCCESS = 'TALLA_DELETE_SUCCESS';
export const TALLA_DELETE_RESET = 'TALLA_DELETE_RESET';

// List types
export const TALLA_LIST_ERROR = 'TALLA_LIST_ERROR';
export const TALLA_LIST_LOADING = 'TALLA_LIST_LOADING';
export const TALLA_LIST_RESET = 'TALLA_LIST_RESET';
export const TALLA_LIST_VIEW = 'TALLA_LIST_VIEW';
export const TALLA_LIST_SUCCESS = 'TALLA_LIST_SUCCESS';
