#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

    defaults:
        template: homepage.html.twig

#api_login_check:
#    path: /login_check

reload:
    path: /{any}
    controller: App\Controller\Security\SecurityController::reloadAction
reload_level_1:
    path: /{any}/create
    controller: App\Controller\Security\SecurityController::reloadAction
reload_level_2:
    path: /{any}/{any2}/{id}
    controller: App\Controller\Security\SecurityController::reloadAction
