#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

    defaults:
        template: homepage.html.twig

reload:
    path: /{any}
    controller: App\Controller\SecurityController::reloadAction
reload_level_1:
    path: /{any}/create
    controller: App\Controller\SecurityController::reloadAction
reload_level_2:
    path: /{any}/edit/{id}
    controller: App\Controller\SecurityController::reloadAction