// Create types
export const PRODUCTO_CREATE_ERROR = 'PRODUCTO_CREATE_ERROR';
export const PRODUCTO_CREATE_LOADING = 'PRODUCTO_CREATE_LOADING';
export const PRODUCTO_CREATE_SUCCESS = 'PRODUCTO_CREATE_SUCCESS';
export const PRODUCTO_CREATE_VIOLATIONS = 'PRODUCTO_CREATE_VIOLATIONS';
export const PRODUCTO_CREATE_RESET = 'PRODUCTO_CREATE_RESET';

// Show types
export const PRODUCTO_SHOW_ERROR = 'PRODUCTO_SHOW_ERROR';
export const PRODUCTO_SHOW_LOADING = 'PRODUCTO_SHOW_LOADING';
export const PRODUCTO_SHOW_RETRIEVED_SUCCESS = 'PRODUCTO_SHOW_RETRIEVED_SUCCESS';
export const PRODUCTO_SHOW_RESET = 'PRODUCTO_SHOW_RESET';

// Update types
export const PRODUCTO_UPDATE_RESET = 'PRODUCTO_UPDATE_RESET';
export const PRODUCTO_UPDATE_UPDATE_ERROR = 'PRODUCTO_UPDATE_UPDATE_ERROR';
export const PRODUCTO_UPDATE_UPDATE_LOADING = 'PRODUCTO_UPDATE_UPDATE_LOADING';
export const PRODUCTO_UPDATE_UPDATE_SUCCESS = 'PRODUCTO_UPDATE_UPDATE_SUCCESS';
export const PRODUCTO_UPDATE_RETRIEVE_ERROR = 'PRODUCTO_UPDATE_RETRIEVE_ERROR';
export const PRODUCTO_UPDATE_RETRIEVE_LOADING = 'PRODUCTO_UPDATE_RETRIEVE_LOADING';
export const PRODUCTO_UPDATE_RETRIEVE_SUCCESS = 'PRODUCTO_UPDATE_RETRIEVE_SUCCESS';
export const PRODUCTO_UPDATE_UPDATE_VIOLATIONS = 'PRODUCTO_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const PRODUCTO_DELETE_ERROR = 'PRODUCTO_DELETE_ERROR';
export const PRODUCTO_DELETE_LOADING = 'PRODUCTO_DELETE_LOADING';
export const PRODUCTO_DELETE_SUCCESS = 'PRODUCTO_DELETE_SUCCESS';
export const PRODUCTO_DELETE_RESET = 'PRODUCTO_DELETE_RESET';

// List types
export const PRODUCTO_LIST_ERROR = 'PRODUCTO_LIST_ERROR';
export const PRODUCTO_LIST_LOADING = 'PRODUCTO_LIST_LOADING';
export const PRODUCTO_LIST_RESET = 'PRODUCTO_LIST_RESET';
export const PRODUCTO_LIST_VIEW = 'PRODUCTO_LIST_VIEW';
export const PRODUCTO_LIST_SUCCESS = 'PRODUCTO_LIST_SUCCESS';
